services:
  - name: scrapeSmart
    type: web
    runtime: node
    plan: free  # Upgrade if needed
    buildCommand: |
      apt-get update && apt-get install -y wget curl unzip fontconfig locales \
      gconf-service libasound2 libatk1.0-0 libcups2 libdrm2 libxkbcommon-x11-0 \
      libgtk-3-0 libgbm-dev libnss3 libxss1 libxtst6 ca-certificates \
      fonts-liberation libappindicator1 libappindicator3-1 libcurl4 \
      libdbus-1-3 libnspr4 lsb-release xdg-utils --no-install-recommends
      npm install --omit=dev
    startCommand: node index.js
    envVars:
      - fromGroup: scrapeSmart-env  # Load all .env variables dynamically
    autoDeploy: true



# services:
#   - name: scrapeSmart
#     type: web
#     runtime: node
#     plan: free  # Change to 'starter' or 'pro' if needed
#     buildCommand: |
#       apt-get update && apt-get install -y wget curl unzip fontconfig locales \
#       gconf-service libasound2 libatk1.0-0 libcups2 libdrm2 libxkbcommon-x11-0 \
#       libgtk-3-0 libgbm-dev libnss3 libxss1 libxtst6 ca-certificates \
#       fonts-liberation libappindicator1 libappindicator3-1 libcurl4 \
#       libdbus-1-3 libnspr4 lsb-release xdg-utils --no-install-recommends
#       npm install --omit=dev
#     startCommand: node index.js
#     envVars:
#       - key: NODE_ENV
#         value: production
#       - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
#         value: true
#       - key: PORT
#         value: 8080  # Change if needed
#     autoDeploy: true
